In [1]:
import pandas as pd
import numpy as np
import setting
from lightgbm import LGBMRegressor
import gc

gc.enable()

DATA = '~/Data/Molecular'

data = pd.concat([
    pd.read_pickle(f"{DATA}/basic.gz"),
    #pd.read_pickle(f"{DATA}/angle_feature.gz"),
    #pd.read_pickle(f"{DATA}/criskiev_distance_feature.gz"),
    #pd.read_pickle(f"{DATA}/qm9.gz")
], axis = 1)

data.drop(columns=[
    'id',
    'molecule_name',
    'atom_index_0',
    'atom_index_1',
    'type',
    'atom_0',
    'x_0',
    'y_0',
    'z_0',
    'atom_1',
    'x_1',
    'y_1',
    'z_1'
], inplace=True)
tdata = data.iloc[4658147:, :]
tdata = tdata.reset_index(drop=True)
data = data.iloc[:4658147, :]



In [3]:
train = pd.read_csv(f"{DATA}/train.csv", dtype={
    'molecule_name': 'category',
    'atom_index_0': 'int8',
    'atom_index_1': 'int8',
    'type': 'category',
    'scalar_coupling_constant': 'float32'
}, usecols=['molecule_name', 'type', 'scalar_coupling_constant'])
test = pd.read_csv(f"{DATA}/test.csv", dtype={
    'molecule_name': 'category',
    'atom_index_0': 'int8',
    'atom_index_1': 'int8',
    'type': 'category'
}, usecols=['type'])
y = train.scalar_coupling_constant

In [24]:
submission = pd.read_csv(f"{DATA}/sample_submission.csv")

In [31]:
from sklearn.model_selection import GroupKFold
from sklearn.metrics import mean_absolute_error

for bond in pd.unique(train['type']):
    X = data[train['type'] == bond]
    Y = y[train['type'] == bond]
    y_pred = np.zeros(tdata.shape[0], dtype='float32')
    gkf = GroupKFold(2)
    for i, (it, iv) in enumerate(gkf.split(X, Y, groups=train[train['type']==bond].molecule_name)):
        lgbm = LGBMRegressor(objective='regression_l1', n_estimators=10000, learning_rate=0.1, subsample_freq=1, \
                         feature_fraction=0.7, subsample=0.7, reg_alpha=0.1, reg_lambda=0.3, device_type='gpu',
                        **setting.param['1JHC'])
        lgbm.fit(
            X.iloc[it],
            Y.iloc[it],
            eval_set=[(X.iloc[it], Y.iloc[it]), (X.iloc[iv], Y.iloc[iv])],
            eval_metric='regression_l1',
            verbose=100,
            early_stopping_rounds=200
        )
        print(f"In fold {i}, a model training stopped at iteration {lgbm.best_iteration_} with score {lgbm.best_score_['valid_1']}. Dumping model as {bond}_fold{i}.lightgbm")
        lgbm.booster_.save_model(f"{bond}_fold{i}.lightgbm")
        y_pred += lgbm.predict(tdata[test['type'] == bond])
    y_pred /= 2
    submission.loc[test['type'] == bond, 'scalar_coupling_constant'] = y_pred

Training until validation scores don't improve for 200 rounds.
[100]	valid_0's l1: 1.29481	valid_1's l1: 1.54186
[200]	valid_0's l1: 1.09396	valid_1's l1: 1.46876
[300]	valid_0's l1: 0.986395	valid_1's l1: 1.44148
[400]	valid_0's l1: 0.9104	valid_1's l1: 1.42368
[500]	valid_0's l1: 0.855832	valid_1's l1: 1.41157
[600]	valid_0's l1: 0.816453	valid_1's l1: 1.40404
[700]	valid_0's l1: 0.785048	valid_1's l1: 1.39858
[800]	valid_0's l1: 0.759677	valid_1's l1: 1.39467
[900]	valid_0's l1: 0.737345	valid_1's l1: 1.39049
[1000]	valid_0's l1: 0.718415	valid_1's l1: 1.38737
[1100]	valid_0's l1: 0.702783	valid_1's l1: 1.38489
[1200]	valid_0's l1: 0.688465	valid_1's l1: 1.3826
[1300]	valid_0's l1: 0.675825	valid_1's l1: 1.38064
[1400]	valid_0's l1: 0.664991	valid_1's l1: 1.37912
[1500]	valid_0's l1: 0.65475	valid_1's l1: 1.37774
[1600]	valid_0's l1: 0.645104	valid_1's l1: 1.3762
[1700]	valid_0's l1: 0.63655	valid_1's l1: 1.37495
[1800]	valid_0's l1: 0.628379	valid_1's l1: 1.37369
[1900]	valid_0's l

ValueError: operands could not be broadcast together with shapes (2505542,) (380609,) (2505542,) 

In [30]:
X.iloc[it]

dist_x    dist_y    dist_z      dist  dist_x_molecule_mean  \
19       1.013577  0.414161  0.007492  1.094954              0.832736   
26       0.523372  0.398029  0.875550  1.094958              0.832736   
32       0.506537  0.388591  0.889591  1.094968              0.832736   
38       0.523383  0.398026  0.875545  1.094958              0.832736   
42       1.013580  0.414152  0.007510  1.094953              0.832736   
45       0.506522  0.388588  0.889600  1.094968              0.832736   
56       1.015643  0.409896  0.007488  1.095263              0.624872   
61       0.524383  0.393654  0.877306  1.095266              0.624872   
65       0.507512  0.383986  0.891387  1.095256              0.624872   
70       0.013976  1.061343  0.005755  1.061451              0.624872   
71       1.019916  0.393771  0.007659  1.093317              0.776069   
76       0.526102  0.377671  0.880868  1.093319              0.776069   
80       0.509192  0.368054  0.894750  1.093306              0.776069   
187      0.597137  0.266183  0.879652  1.095999              1.005763   
192      1.012302  0.389837  0.111224  1.090458              1.005763   
196      0.484098  0.470203  0.863592  1.096008              1.005763   
201      0.528063  0.397237  0.874396  1.096000              1.005763   
206      0.148133  1.074033  0.116654  1.090458              1.005763   
210      0.639768  0.192447  0.868844  1.096007              1.005763   
211      0.907104  0.429540  0.435330  1.094009              0.984032   
216      0.877608  0.411545  0.497781  1.089656              0.984032   
220      0.035060  0.285475  1.057162  1.095589              0.984032   
230      1.007386  0.433927  0.005461  1.096882              0.965178   
237      0.529809  0.382107  0.879099  1.095225              0.965178   
243      0.516014  0.372468  0.891336  1.095209              0.965178   
249      1.031343  0.380564  0.007966  1.099345              0.965178   
260      1.036945  0.352696  0.059727  1.096912              0.965178   
266      0.020711  1.094719  0.026427  1.095234              0.965178   
271      0.520086  0.347708  0.898986  1.095247              0.965178   
276      0.502370  0.338389  0.912544  1.095271              0.965178   
...           ...       ...       ...       ...                   ...   
4657828  0.861415  0.331780  0.583276  1.091936              1.389277   
4657837  0.439941  0.235007  0.970773  1.091411              1.389277   
4657847  0.012943  1.079904  0.054957  1.081379              1.389277   
4657857  0.972332  0.473762  0.063234  1.083457              1.389277   
4657869  0.593437  0.805558  0.440747  1.093320              1.389277   
4657878  0.210935  0.072795  1.070561  1.093569              1.389277   
4657889  0.237741  0.415037  0.970014  1.081528              1.389277   
4657953  0.021821  0.200223  1.074388  1.093104              1.395282   
4657962  0.673372  0.826574  0.240653  1.092963              1.395282   
4657971  0.989137  0.440593  0.038740  1.083520              1.395282   
4657980  0.006423  1.078162  0.109968  1.083775              1.395282   
4657990  0.590584  0.283985  0.867753  1.087397              1.395282   
4657998  0.922767  0.088482  0.573382  1.089998              1.395282   
4658009  0.243378  0.829194  0.660286  1.087554              1.395282   
4658011  0.736329  0.806311  0.015039  1.092037              1.299444   
4658019  0.414048  0.157173  0.998201  1.092037              1.299444   
4658028  0.858368  0.404438  0.520320  1.082173              1.299444   
4658039  0.065299  1.068662  0.157465  1.082173              1.299444   
4658049  0.888309  0.238982  0.580075  1.087517              1.299444   
4658057  0.627838  0.147804  0.879467  1.090637              1.299444   
4658068  0.414568  0.852229  0.533415  1.087517              1.299444   
4658069  0.654103  0.043565  0.874958  1.093298              1.331285   
4658076  0.103361  0.897007  0.616439  1.093298              1.331285

In [28]:
iv

array([     0,      1,      2, ..., 709390, 709391, 709392])

In [20]:
for it, iv in gkf.split(data[train['type']=='3JHC'], y[train['type']=='3JHC'], groups=train[train['type']=='3JHC'].molecule_name):
    pass

In [21]:
it

array([     11,      12,      13, ..., 1510376, 1510377, 1510378])

In [22]:
iv

array([      0,       1,       2, ..., 1510316, 1510317, 1510318])